// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9_qk6gEh0o6qQzBlvaIoIhcUCWkNQ-mQ',
    appId: '1:261069155360:web:1db8a58ca41febc0a5e045',
    messagingSenderId: '261069155360',
    projectId: 'faunty-2-0',
    authDomain: 'faunty-2-0.firebaseapp.com',
    storageBucket: 'faunty-2-0.firebasestorage.app',
    measurementId: 'G-ZF2W5PFE3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDymUHTLtw837ryfnGFftWHVNfniBktllU',
    appId: '1:261069155360:android:da6d5265b2c92ab8a5e045',
    messagingSenderId: '261069155360',
    projectId: 'faunty-2-0',
    storageBucket: 'faunty-2-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSR-K_2hDgxVuYbrbZBopfF8iGVSLinSs',
    appId: '1:261069155360:ios:1b17949f1b57cb66a5e045',
    messagingSenderId: '261069155360',
    projectId: 'faunty-2-0',
    storageBucket: 'faunty-2-0.firebasestorage.app',
    iosBundleId: 'com.example.faunty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSR-K_2hDgxVuYbrbZBopfF8iGVSLinSs',
    appId: '1:261069155360:ios:1b17949f1b57cb66a5e045',
    messagingSenderId: '261069155360',
    projectId: 'faunty-2-0',
    storageBucket: 'faunty-2-0.firebasestorage.app',
    iosBundleId: 'com.example.faunty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9_qk6gEh0o6qQzBlvaIoIhcUCWkNQ-mQ',
    appId: '1:261069155360:web:2e22e6f9695503baa5e045',
    messagingSenderId: '261069155360',
    projectId: 'faunty-2-0',
    authDomain: 'faunty-2-0.firebaseapp.com',
    storageBucket: 'faunty-2-0.firebasestorage.app',
    measurementId: 'G-Q0HT0E46D8',
  );
}
